# npm commands for dev on mac os x


# Start Vite development server with hot reloading
dev:
	npm run dev

# Sideload the add-in using office-addin-debugging
# (use a different terminal than `make dev`)
start:
	npm run start

# stop debugging session
stop:
	npm run stop

# install development certificates (do only once)
certs:
	npm run dev-certs

build:
	npm run build
